import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'navbar_model.freezed.dart';

@freezed
class NavbarModel with _$NavbarModel {
  const factory NavbarModel({required int currentIndex, required List pages}) =
      _NavbarModel;
}
