// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'portfolio_model.freezed.dart';

@freezed
class PortfolioModel with _$PortfolioModel {
  const factory PortfolioModel({
    required List<Stock> stocks,
  }) = _PortfolioModel;
}

class Stock {
  final String name;
  final double holding;
  final double change;

  Stock({required this.name, required this.holding, required this.change});

  static List<Stock> getAll() {
    List<Stock> stocks = <Stock>[];
    stocks.add(Stock(name: "test", holding: 500.13, change: 3.2));
    stocks.add(Stock(name: "bitcoin", holding: 2424.43, change: 3.2));
    stocks.add(Stock(name: "Doge", holding: 452.13, change: 3.2));
    stocks.add(Stock(name: "Eterium", holding: 630.13, change: 3.2));

    return stocks;
  }
}
